name: Release

on:
  push:
    tags:
      - "*"

jobs:

  release:

    runs-on: macos-latest

    steps:
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
